<center> <img src = https://avatars.mds.yandex.net/i?id=f20ebff1ac987027d1121f689c9f36a01e4e501d-4491734-images-thumbs&n=13 alt="drawing" style="width:400px;">

# <CENTER> **Бриф «Лаборатории исследований гражданского общества». Определение уязвимых групп населения**

Согласно [опросу «инФОМ»](https://www.cbr.ru/Collection/Collection/File/39633/inFOM_21-12.pdf) от декабря 2021 года, у `27%` россиян хватает денег только на еду, а еще `9%` не могу позволить себе полноценное питание. Эти люди особенно внимательно следят за ценами. а темп роста цен на продукты обычно превышает средний темп инфляции. При этом Росстат [считает](https://www.fedstat.ru/indicator/37053), что расходы на продукты питания должны составлять примерно `36%` от среднемесячных расходов россиянина (ещё около `10%` приходится на услуги ЖКХ и жильё, `4%` — на лекарства).

До 2021 года «черта бедности» (жизнь на сумму ниже прожиточного минимума) в России определялась стоимостью [минимальной продуктовой корзины](https://base.garant.ru/70306880/). В том же году правительство «отвязало» уровень бедности от цен на базовые продукты: с 2021 года прожиточный минимум рассчитывается как `44.2%` от медианного дохода граждан РФ за прошлый год

В распоряжении есть данные о доходах, заболеваемости, социально незащищённых слоях населения России и другие экономические и демографические данные.

Подробное техническое задание находится в файле ->
`Бриф__Лаборатории_исследований_гражданского_общества__Определение_уязвимых_групп_населения.pdf`

> ### ⭐**Ваша задача:**

-   кластеризовать регионы Россиии определить, какие из них наиболее остро нуждаются в помощи малообеспеченным/неблагополучным слоям населения;

-   описать группы населения, сталкивающиеся с бедностью;

-   определить:

        ➔   влияет ли число детей, пенсионеров и других социально уязвимых групп на уровень бедности в регионе;

        ➔   связаны ли уровень бедности/социального неблагополучия с производством и потреблением в регионе;

        ➔   какие ещё зависимости можно наблюдать относительно социально незащищённых слоёв населения.

> ###  **Данные**

Предоставленные таблицы:

-   `child_mortality_rural_1990_2021.xls` — число умерших на первом году жизни детей за год, по всем регионам, в сельской местности.

-   `child_mortality_urban_1990_2021.xls` — число умерших на первом году жизни детей за год, по всем регионам, в городской местности.

-   `disabled_total_by_age_2017_2022.csv` — число людей с инвалидностью по регионам, по месяцам, по возрастным группам.

-   `morbidity_2005_2020_age_disease.xls` — заболеваемость на 100 тыс. человек населения, по возрастным группам и группам заболеваний.

-   `poverty_percent_by_regions_1992_2020.csv` — процент людей, живущих за чертой бедности (с денежными доходами ниже величины прожиточного минимума), оценка за год по регионам.

-   `welfare_expense_share_2015_2020` — расходы на социальную политику от общих расходов бюджета региона, % в год*.

-   `cash_real_income_wages_2015_2020` — среднедушевые и реальные денежные доходы населения, номинальная и реальная начисленная зарплата, по регионам*.

-   `poverty_socdem_20*.xls` — распределение малоимущего населения по социально-демографическим группам (дети, трудящиеся, пенсионеры) за 2017–2020 гг., по регионам.

-   `housing_2020` — характеристика жилищных условий домохозяйств. Оценка домохозяйствами состояния занимаемого ими жилого помещения, обследование 2020 года*.

-   `population.xlsx` — численность населения по регионам и федеральным округам на 1 января каждого года за 1999–2022 гг.

-   `gross_regional_product_1996_2020.xls` — валовой региональный продукт на душу населения, в рублях.

-   `regional_production_*_*.csv` — объём отгруженных товаров собственного производства или работ/услуг, выполненных собственными силами, по видам деятельности за 2005–2016 гг., 2017–2020 гг. (в тысячах рублей, значение показателя за год, полный круг).

-   `retail_turnover_per_capita_2000_2021.xls` — оборот розничной торговли на душу населения, в рублях.

-   `drug_alco` — сведения о заболеваемости алкоголизмом и наркоманией, на 100 тыс. населения (2005–2018):

-    `newborn_2006_2022_monthly.csv` — рождённые в этом месяце, по регионам, без учёта мертворождённых

-    `workers.csv` — отношение числа занятых в экономике региона к численности населения региона в трудоспособном возрасте, %, 2012–2020гг.

> ### **Папка crimes**

Сведения о преступлениях, совершённых отдельными категориями лиц за 2016–2022 гг., по месяцам, регионам, категориям лиц, категориям преступлений:

1. В папке содержатся файлы о расследованных преступлениях (число преступлений).

2. Файлы представлены в том виде, в котором их предоставляет Генпрокуратура. С ними требуется поработать, чтобы привести их в пригодный для анализа вид.

3. Данные за каждый месяц агрегированы с предыдущими месяцами этого года (то есть январь 2022, далее — январь + февраль 2022 и так далее).

4. Файлы содержат указание на месяц в названии файла по типу `4-EGS_Razdel_%_%MMYYYY%.xls` (в названии может быть раздел 4 или 5). Это связано с тем, что форма статистического наблюдения изменилась с 2021 года, поэтому файлы различаются, однако по большому срезу данных в них представлена схожая информация.

>### ⭐**Стоит обратить вимание на:**

1. Методологии подсчёта некоторых показателей могли меняться за время их наблюдения.

2. Не всегда один и тот же регион пишется одинаково в разных датасетах. Это необходимо учитывать при объединении датасетов.

3. Особенностью Тюменской области является то, что в её состав входят два других субъекта Российской Федерации: Ханты-Мансийский автономный округ — Югра и Ямало-Ненецкий автономный округ. При этом чаще всего в датасетах указывается отдельно Тюменская область и отдельно — без учёта автономных округов.

4. То же самое касается Архангельской области — в её состав входит самостоятельный субъект Ненецкий автономный округ. Способы написания такие же, как с Тюменской областью.

5. Нежелательно использовать данные по федеральному округу в совокупности. Во-первых, это агрегированные данные, и чаще всего по ним нельзя сделать никаких интересных выводов, а во-вторых, на протяжении последних 20 лет составы федеральных округов менялись, из-за чего в них мог произойти резкий рост/снижение численности населения, что не отражало какое-то демографическое явление.

>**Важное примечание!**

В исследовании приведеные разные временные интервалы, вне зависимости от типа данных и их структуры. 

Так как мы определяем уязвимую группу населения РФ, необходимо ориентироваться на самые актуальные данные, что вполне логично и думаю не требует подробному объяснению. Как будет известно далее данные за 2016-2022 годы представленные более полно.

---

> ### <center>**ОРГАНИАЦИЯ ПРОЕКТА**

#### **Часть 1. Подготовка данных**
> **Подготовка окружения и обзор данных**: Загрузка всех файлов, проверка структуры, нормализация названий регионов.

> **Предобработка данных**: Очистка данных, обработка пропусков, агрегация по времени (период: 2017–2020, с использованием среднего или последнего года в зависимости от контекста).

#### **Часть 2. Анализ и моделирование**
> **Исследовательский анализ данных (EDA)**: Визуализация распределений, корреляций и выявление паттернов.

> **Selection**: Применение PCA для снижения размерности.

> **Кластеризация регионов**: Применение алгоритмов кластеризации, оценка результатов.

#### **Часть 3. Результаты кластеризации**
> **Анализ зависимостей**: Оценка влияния демографических групп и экономических факторов на бедность.

> **Выводы**: Подведение итогов.

---

> ## <Center>**Часть 1. Подготовка данных**

In [1]:
# Импорт библиотек 
import re
import pandas as pd
import numpy as np

# отключаем предупреждения
import warnings
warnings.filterwarnings("ignore")

#### `Словарь стандартных названий `

In [2]:
standard_names = {
    # Для автономных округов 
    r'хант.*югра.*': 'Ханты-Мансийский автономный округ - Югра',
    r'хант.*мансийский.*авт.*округ': 'Ханты-Мансийский автономный округ - Югра',
    r'хант.*мансийский.*': 'Ханты-Мансийский автономный округ - Югра',

    r'ямал.*ненецк.*': 'Ямало-Ненецкий автономный округ',
    r'ямал.*hенецк.*': 'Ямало-Ненецкий автономный округ', # исключение
    r'ненецк.*': 'Ненецкий автономный округ',
    
    # Для регионов РФ 
    r'тюменск.*': 'Тюменская область',  
    r'архангельск.*': 'Архангельская область',  # Аналогично
    r'адыгей?': 'Республика Адыгея',
    r'республ.*алтай': 'Республика Алтай',  
    r'башкортостан': 'Республика Башкортостан',
    r'бурятия': 'Республика Бурятия',
    r'дагестан': 'Республика Дагестан',
    r'ингушетия': 'Республика Ингушетия',
    r'кабардино-балкар.*': 'Кабардино-Балкарская Республика',
    r'калмыкия': 'Республика Калмыкия',
    r'карачаево-черкес.*': 'Карачаево-Черкесская Республика',
    r'карелия': 'Республика Карелия',
    r'республ.*коми': 'Республика Коми',
    r'республ.*крым': 'Республика Крым',
    r'марий.*': 'Республика Марий Эл',
    r'мордовия': 'Республика Мордовия',
    r'сахалинск.*': 'Сахалинская область',
    r'саха|якутия': 'Республика Саха (Якутия)',
    r'северн.*осетия': 'Республика Северная Осетия — Алания',
    r'татарстан': 'Республика Татарстан',
    r'тыва': 'Республика Тыва',
    r'удмурт.*': 'Удмуртская Республика',
    r'хакасия': 'Республика Хакасия',
    r'чуваш.*': 'Чувашская Республика — Чувашия',
    r'алтайск.*': 'Алтайский край',
    r'забайкал.*': 'Забайкальский край',
    r'камчатск.*край': 'Камчатский край',
    r'краснодарск.*': 'Краснодарский край',
    r'красноярск.*': 'Красноярский край',
    r'пермск.*край': 'Пермский край',
    r'приморск.*': 'Приморский край',
    r'ставропол.*': 'Ставропольский край',
    r'хабаровск.*': 'Хабаровский край',
    r'амурск.*': 'Амурская область',
    r'астраханск.*': 'Астраханская область',
    r'белгородск.*': 'Белгородская область',
    r'брянск.*': 'Брянская область',
    r'владимирск.*': 'Владимирская область',
    r'bладимирск.*': 'Владимирская область', # исключение
    r'волгоградск.*': 'Волгоградская область',
    r'bолгоградск.*': 'Волгоградская область', # исключение
    r'вологодск.*': 'Вологодская область',
    r'bологодск.*': 'Вологодская область', # исключение
    r'воронежск.*': 'Воронежская область',
    r'bоронежск.*': 'Воронежская область', # исключение
    r'ивановск.*': 'Ивановская область',
    r'иркутск.*': 'Иркутская область',
    r'калининградск.*': 'Калининградская область',
    r'калу?жск.*': 'Калужская область',
    r'кемеровск.*': 'Кемеровская область — Кузбасс',
    r'кировск.*': 'Кировская область',
    r'костромск.*': 'Костромская область',
    r'кур?ганск.*': 'Курганская область',
    r'курск.*': 'Курская область',
    r'ленинградск.*': 'Ленинградская область',
    r'липецк.*': 'Липецкая область',
    r'магаданск.*': 'Магаданская область',
    r'московск.*(?!город)': 'Московская область',
    r'мурманск.*': 'Мурманская область',
    r'нижегородск.*': 'Нижегородская область',
    r'новгородск.*': 'Новгородская область',
    r'новосибирск.*': 'Новосибирская область',
    r'оренбургск.*': 'Оренбургская область',
    r'орловск.*': 'Орловская область',
    r'пензенск.*': 'Пензенская область',
    r'псковск.*': 'Псковская область',
    r'ростовск.*': 'Ростовская область',
    r'рязанск.*': 'Рязанская область',
    r'самарск.*': 'Самарская область',
    r'саратовск.*': 'Саратовская область',
    r'свердловск.*': 'Свердловская область',
    r'смоленск.*': 'Смоленская область',
    r'тамбовск.*': 'Тамбовская область',
    r'тверск.*': 'Тверская область',
    r'томск.*': 'Томская область',
    r'тульск.*': 'Тульская область',
    r'ульяновск.*': 'Ульяновская область',
    r'челябинск.*': 'Челябинская область',
    r'ярославск.*': 'Ярославская область',
    r'москва': 'Москва',
    r'санкт.*петербург': 'Санкт-Петербург',
    r'севастопол.*': 'Севастополь',
    r'еврейск.*авт.*': 'Еврейская автономная область',
    r'чукотск.*': 'Чукотский автономный округ',
    r'омск.*': 'Омская область',
    r'чеченская республика': 'Чеченская Республика'
}

#### `Функция для извлечения данных и стандартизации названия регионов.`

In [3]:
def process_region_data(dataframe, standard_names_dict, exclude_list=None, region_column='region'):
    """
    Обрабатывает данные по федеральным субъектам, стандартизируя названия регионов.
    
    Args:
        dataframe (pd.DataFrame): Входной DataFrame с данными.
        standard_names_dict (dict): Словарь соответствия нестандартных названий стандартным.
        exclude_list (list, optional): Список названий регионов для исключения.
        region_column (str, optional): Название столбца с регионами. По умолчанию 'region'.
    
    Returns:
        pd.DataFrame: Обработанный DataFrame с стандартизированными названиями регионов.
    """
    
    def standardize_region_name(region_name):
        """Преобразует название региона в стандартный вид."""
        if pd.isna(region_name):
            return None
        # Удаляем текст в скобках и лишние пробелы
        cleaned_name = re.sub(r'\s*\([^)]+\)', '', str(region_name)).strip()
        # Удаляем переносы строк
        cleaned_name = cleaned_name.replace('\n', ' ')
        # Также заменяем множественные пробелы на один
        cleaned_name = re.sub(r'\s+', ' ', cleaned_name)
        
        # Поиск совпадения с ключами словаря (игнорируя регистр)
        for pattern, standard_name in standard_names_dict.items():
            if re.search(pattern.lower(), cleaned_name.lower()):
                return standard_name
        return None
    
    # Копируем DataFrame для избежания изменения исходных данных
    df = dataframe.copy()
    
    # Исключаем регионы из списка исключений, если он задан
    if exclude_list is not None:
        df = df[~df[region_column].isin(exclude_list)]

    # Применяем стандартизацию названий
    df[region_column] = df[region_column].apply(standardize_region_name)
    
    # Удаляем строки с отсутствующими или нераспознанными регионами
    df = df.dropna(subset=[region_column])
    
    # Устанавливаем регион как индекс и сортируем
    return df.set_index(region_column).sort_index()

### **1.1 Население и демография**

> **population.xlsx** - Численность населения по регионам и федеральным округам на 1 января каждого года за 1999–2022 гг.

Файл population.xlsx содержит иерархию — от Российской Федерации и федеральных округов до субъектов, а затем до муниципалитетов и населённых пунктов. Для анализа нужны только субъекты и автономные округи. а остальные уровни нерелевантны.

Автономные округи РФ:
-   Чукотский автономный округ является отдельным субъектом РФ
-   Эвенкийский АО - вошёл в состав Красноярского края (2007) `(не будем учитывать)`
-   Ямало-Ненецкий АО - входит в Тюменскую область.
-   Ханты-Мансийский автономный округ - Югра (Тюменская область). Так как входит в состав тюменской области, необходимо найти численность населения Тюменской области, не включая ХМАО и ЯНАО.
-   Таймырский (Долгано-Ненецкий) АО - вошёл в состав Красноярского края (2007) `(не будем учитывать)`
-    Ненецкий АО - входит в Архангельскую область. Необходимо найти численность населения Тюменской области, не включая ХМАО и ЯНАО.

Так как мы будем учитывать в исследовании автономные округи, соответсвенно нас будут интересовать регионы без учета входящих в них АО. Иначе, мы получим агрегированные данные.

Также будем рассматривать относительно свежие данные (с 2016 по 2022).

In [4]:
path = 'social_russia_data/population.xlsx'
population = pd.read_excel(
        path,
        header=1,
        usecols='A, T:Z')
population.rename({'Unnamed: 0': 'region'}, axis=1, inplace=True)

# Корректировка названий регионов (замена разделов на предыдущие регионы)
for i, val in enumerate(population['region']):
    if val == 'Раздел 1. Муниципальные образования субъектов Российской Федерации':
        population.loc[i, 'region'] = population.loc[i-1, 'region']
population.dropna(subset=population.columns[1:], how='all', inplace=True)

# Список регионов для исключения
names_to_drop = [
    'Архангельская область', # удаляем агрегированные данные
    'Тюменская область', # удаляем агрегированные данные
    'Муниципальные образования Алтайского края',
    'Алтайский муниципальный район',
    'Алтайский сельсовет',
    'Большекалтайский сельсовет',
    'Населенные пункты, входящие в состав муниципальных образований Алтайского края',
    'Кировский сельсовет'
]

# Стандартизация регионов с помощью нашей функции
population = process_region_data(population, standard_names, names_to_drop, region_column='region')

# Преобразование названий колонок в годы
newcols = []
for col in population.columns:
    newcols.append(re.search(r'\d+', col).group(0))
population.columns = pd.to_datetime(newcols).year

# display(population.head())
population.info()

<class 'pandas.core.frame.DataFrame'>
Index: 85 entries, Алтайский край to Ярославская область
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2016    85 non-null     float64
 1   2017    85 non-null     float64
 2   2018    85 non-null     float64
 3   2019    85 non-null     float64
 4   2020    85 non-null     float64
 5   2021    85 non-null     float64
 6   2022    85 non-null     float64
dtypes: float64(7)
memory usage: 5.3+ KB

По итогу получили таблицу численности населения по регионам РФ. Всего 85 регионов (2016-2022), данные не агрегированны.

---

> **newborn_2006_2022_monthly.csv** — рождённые в этом месяце, по регионам, без учёта мертворождённых.

In [5]:
path = "social_russia_data/newborn_2006_2022_monthly.csv"
newborn = pd.read_csv(path, sep=';', decimal=',')
newborn.drop(columns='Unnamed: 198', inplace=True)

names_to_drop = [
    'Архангельская область', # удаляем агрегированные данные
    'Тюменская область', # удаляем агрегированные данные
    'Московская обл. в старых границах',
    'Москва в старых границах'
]

newborn = process_region_data(newborn,
                              standard_names,
                              names_to_drop,
                              region_column='Region').reset_index()


for year in range(2006, 2023):
    cols = [] # список всех столбцов относящихся к оапределнному году
    for col in newborn.columns:
        if str(year) in str(col):
            cols.append(col)
    # создаем столбец рождаемость года и суммируем значения        
    newborn[year] = newborn[cols].sum(axis=1)
    # удаляем месячные столбцы
    newborn = newborn.drop(columns=cols, axis=1)

# удалим 2022 год - данные неполные
newborn.drop(2022, axis=1, inplace=True)

newborn.set_index('Region', inplace=True)
display(newborn.describe().round())

,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
count,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0
mean,17014.0,18465.0,19799.0,20336.0,20630.0,20683.0,21866.0,21923.0,22566.0,22872.0,22274.0,19881.0,18878.0,17465.0,16891.0,16504.0
std,15575.0,16820.0,18255.0,19156.0,19905.0,20201.0,21592.0,21888.0,22156.0,22456.0,22555.0,20580.0,19919.0,19296.0,18355.0,18586.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,683.0,671.0,658.0,608.0,526.0,537.0,521.0
25%,7391.0,7696.0,8220.0,8260.0,8309.0,8255.0,8650.0,8604.0,9164.0,9099.0,8566.0,8000.0,7438.0,6835.0,6642.0,6629.0
50%,12046.0,13070.0,14148.0,14343.0,14168.0,13948.0,14777.0,14798.0,15033.0,15025.0,14605.0,12797.0,11998.0,11005.0,10584.0,10138.0
75%,23717.0,26130.0,27492.0,28194.0,28697.0,28055.0,29736.0,29844.0,29577.0,28739.0,27307.0,23616.0,22466.0,20821.0,19663.0,18992.0
max,94055.0,100771.0,107779.0,115786.0,123142.0,126655.0,134653.0,136021.0,137583.0,142390.0,145252.0,133889.0,132970.0,136357.0,123524.0,131445.0

---

> **child_mortality_urban_1990_2021.xls** — число умерших на первом году жизни детей за год, по всем регионам, в городской местности.
> **child_mortality_rural_1990_2021.xls** — число умерших на первом году жизни детей за год, по всем регионам, в сельской местности.

Будем использовать сумму числа умерших детей сельской и городской местности.

In [6]:
# считываем данные 
def child_mortality_func(path):
    data = pd.read_excel(path, header=2, usecols='A, D:AI')
    data.rename({'Unnamed: 0': 'region'}, axis=1, inplace=True)
    
    names_to_drop = [
        '        Архангельская область', # удаляем агрегированные данные
        '        Тюменская область'] # удаляем агрегированные данные
    
    data = process_region_data(data, standard_names, names_to_drop)
    return data

rural = child_mortality_func('social_russia_data/child_mortality_rural_1990_2021.xls')
urban = child_mortality_func('social_russia_data/child_mortality_urban_1990_2021.xls')

# Проверяем соответствие и уникальность регионов
if not rural.index.equals(urban.index):
    print("Внимание: Индексы регионов в rural и urban не совпадают!")

# Суммируем данные по годам
child_mortality = rural.add(urban, fill_value=0)

# обрабатываем пропуски за 2021 год
mask_isnull = child_mortality['2021'].isnull()
child_mortality.loc[mask_isnull, '2021'] = child_mortality.loc[mask_isnull, '2020']

child_mortality.head()

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
region,,,,,,,,,,,,,,,,,,,,,
Алтайский край,522.0,567.0,529.0,560.0,497.0,490.0,405.0,375.0,340.0,391.0,...,330.0,290.0,275.0,222.0,211.0,185.0,176.0,114.0,97.0,88.0
Амурская область,343.0,293.0,280.0,244.0,242.0,250.0,245.0,268.0,246.0,270.0,...,161.0,119.0,101.0,83.0,53.0,48.0,46.0,43.0,42.0,36.0
Архангельская область,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,113.0,97.0,84.0,79.0,72.0,53.0,58.0,29.0,32.0
Астраханская область,250.0,235.0,188.0,216.0,202.0,194.0,192.0,188.0,221.0,154.0,...,142.0,130.0,148.0,119.0,82.0,74.0,71.0,72.0,64.0,46.0
Белгородская область,312.0,290.0,240.0,244.0,233.0,203.0,174.0,167.0,160.0,161.0,...,127.0,116.0,103.0,110.0,108.0,77.0,73.0,39.0,47.0,54.0

### **1.2 Бедность и доходы**

> **poverty_percent_by_regions_1992_2020.csv** — процент людей, живущих за чертой бедности, оценка за год по регионам.

 До 2021 года «черта бедности» (жизнь на сумму ниже прожиточного
 минимума) в России определялась стоимостью минимальной продуктовой
 корзины.В том же году правительство «отвязало» уровень бедности от цен на
 базовые продукты: с 2021 года прожиточный минимум рассчитывается как
 44.2% от медианного дохода граждан РФ за прошлый год.

In [7]:
poverty_percent = pd.read_csv('social_russia_data/poverty_percent_by_regions_1992_2020.csv')

poverty_percent = process_region_data(poverty_percent,
                                      standard_names,
                                      names_to_drop).reset_index()

poverty_percent = pd.pivot_table(
    poverty_percent,
    values='poverty_percent',
    columns='year',
    index='region'
)
poverty_percent.describe().round()

year,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
count,82.0,82.0,82.0,82.0,82.0,82.0,82.0,82.0,83.0,83.0,...,83.0,83.0,83.0,83.0,85.0,85.0,85.0,85.0,85.0,85.0
mean,30.0,28.0,25.0,30.0,38.0,41.0,37.0,32.0,28.0,25.0,...,15.0,13.0,14.0,14.0,15.0,15.0,15.0,14.0,14.0,14.0
std,16.0,16.0,13.0,15.0,17.0,15.0,14.0,12.0,11.0,10.0,...,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,...,0.0,6.0,6.0,7.0,7.0,7.0,6.0,6.0,6.0,5.0
25%,22.0,20.0,19.0,22.0,29.0,31.0,27.0,24.0,21.0,19.0,...,12.0,10.0,11.0,11.0,12.0,12.0,11.0,10.0,11.0,10.0
50%,28.0,25.0,23.0,27.0,35.0,39.0,37.0,31.0,28.0,23.0,...,15.0,12.0,13.0,13.0,14.0,15.0,14.0,14.0,14.0,13.0
75%,34.0,31.0,29.0,36.0,47.0,50.0,45.0,39.0,33.0,29.0,...,18.0,16.0,16.0,15.0,17.0,18.0,17.0,16.0,16.0,16.0
max,98.0,91.0,70.0,74.0,90.0,94.0,88.0,87.0,80.0,69.0,...,36.0,31.0,33.0,35.0,37.0,38.0,36.0,34.0,34.0,32.0

---

> **poverty_socdem_2017-2020.xls** — распределение малоимущего населения по социально-демографическим группам (дети, трудящиеся, пенсионеры) за 2017–2020 гг., по регионам.

В данных пристутсвуют пропуски и нулевые значения. Соответсвенно их необходимо обработать, так как мера измерения - проценты % ,соответсвенно, в сумме по всем группам должно быть 100% (удалим неинформативный приизнак "Все население").

`Общий вид уравнения:`
$$r = x + y + z$$
,где $r$ (100% населения региона)
 $x$ (процентов детей в возрасте до 16 лет)
 $y$ (процентов населения старше трудоспособного возраста)
 $z$ (процентов населения трудоспособного возраста)

Пропуски обнаруженны в 2019 году и 2020 году.

Заполнение данных: (под пропуском будем подразумевать null или 0)
-   если пропусков >= 2, то заполняем полностью строку прошлогодними данными 

`В результате будем использовать poverty_socdem_2020.`

In [8]:
# Функция для чтения файлов
def poverty_socdem_func(path):
    data = pd.read_excel(path, header=2)
    data.rename({
        'Unnamed: 0': 'region',
        'Все население': 'all',
        'Дети в возрасте до 16 лет': 'children',
        'Население старше трудоспособного возраста': 'pensioners',
        'Население трудоспособного возраста': 'labouring'},
        axis=1, inplace=True)
    
    data.drop('all', axis=1, inplace=True) # удалим неинформативный признак
    names_to_drop = [
        '        Архангельская область',
        '        Тюменская область'
    ]
    
    data = process_region_data(data, standard_names, names_to_drop)
    return data

poverty_socdem_2017 = poverty_socdem_func('social_russia_data/poverty_socdem_2017.xls')
poverty_socdem_2018 = poverty_socdem_func('social_russia_data/poverty_socdem_2018.xls')
poverty_socdem_2019 = poverty_socdem_func('social_russia_data/poverty_socdem_2019.xls')
poverty_socdem_2020 = poverty_socdem_func('social_russia_data/poverty_socdem_2020.xls')

def missing_socdem(data):
    # Считаем количество пропусков и нулей в каждой строке
    missing_count = (data[['children', 'pensioners', 'labouring']].isnull() | 
                    (data[['children', 'pensioners', 'labouring']] == 0)).sum(axis=1)
    
    # исключаем, когда нет пропусков
    mask = (missing_count == 0) | (missing_count == 1)
    missing_count = missing_count[~mask] 
    
    return missing_count

# cводная таблица количетсва пропусков для 2019
missing_count = missing_socdem(poverty_socdem_2019) 

# заполняем пропущенные значения 
mask = poverty_socdem_2019.index.isin(missing_count.index)
poverty_socdem_2019[mask] = poverty_socdem_2018[mask]

# cводная таблица количетсва пропусков для 2020
missing_count = missing_socdem(poverty_socdem_2020) 

# заполняем пропущенные значения 
mask = poverty_socdem_2020.index.isin(missing_count.index)
poverty_socdem_2020[mask] = poverty_socdem_2019[mask]

display(poverty_socdem_2019.describe().round())
display(poverty_socdem_2020.describe().round())

       children  pensioners  labouring
count      85.0        85.0       85.0
mean       40.0         7.0       53.0
std         6.0         4.0        5.0
min        19.0         0.0       39.0
25%        38.0         5.0       50.0
50%        41.0         6.0       52.0
75%        44.0         9.0       56.0
max        54.0        18.0       65.0

       children  pensioners  labouring
count      85.0        85.0       85.0
mean       39.0         5.0       56.0
std         7.0         4.0        6.0
min        19.0         0.0       42.0
25%        34.0         3.0       52.0
50%        39.0         5.0       55.0
75%        44.0         7.0       59.0
max        56.0        18.0       74.0

---

> **cash_real_income_wages_2015_2020.xlsx** — среднедушевые и реальные денежные доходы населения, номинальная и реальная начисленная зарплата, по регионам*.

**В файле представленны 4 таблицы:**

-   *per_capita_cash_income* — Среднедушевые денежные доходы (в месяц), руб.
-   *real_incomes* — Реальные денежные доходы, в процентах к предыдущему году
-   *formal_wage_paid* — Среднемесячная номинальная начисленная заработная плата, руб.
-   *real_pay* — Реальная начисленная заработная плата, в процентах к предыдущему году

In [9]:
def readout_cash_real_income(path, sheet):
    data = pd.read_excel(path, sheet_name=sheet)
    data = process_region_data(data, standard_names, names_to_drop)
    return data


names_to_drop = [
    'Архангельская область', # удаляем агрегированные данные
    'Тюменская область' # удаляем агрегированные данные
]
path = 'social_russia_data/cash_real_income_wages_2015_2020.xlsx'

per_capita_cash_income = readout_cash_real_income(path, sheet=0)
display('Среднедушевые денежные доходы (в месяц), руб.',
        per_capita_cash_income.head(3))

real_income = readout_cash_real_income(path, sheet=1)
display('Реальные денежные доходы, в процентах к предыдущему году',
        real_income.head(3))

formal_wage_paid = readout_cash_real_income(path, sheet=2)
display('Cреднемесячная номинальная начисленная заработная плата, руб.',
        formal_wage_paid.head(3))

real_pay = readout_cash_real_income(path, sheet=3)
display('Реальная начисленная заработная плата, в процентах к предыдущему году',
        real_pay.head(3))

'Среднедушевые денежные доходы (в месяц), руб.'

                          2015     2016     2017     2018     2019     2020
region
Алтайский край         20860.0  21256.0  22139.0  22829.0  23937.0  23864.0
Амурская область       28240.0  27976.0  29213.0  30937.0  33304.0  35499.0
Архангельская область  29716.0  29837.0  30707.0  32054.0  33874.0  34852.0

'Реальные денежные доходы, в процентах к предыдущему году'

                       2015  2016   2017   2018   2019   2020
region
Алтайский край         99.1  94.7  100.0   99.7   99.6   95.5
Амурская область       96.1  92.1  101.1  102.4  101.7  100.3
Архангельская область  95.1  93.0   98.7  101.7  100.2   98.4

'Cреднемесячная номинальная начисленная заработная плата, руб.'

                          2015     2016     2017     2018     2019     2020
region
Алтайский край         20090.0  21202.0  22743.0  25519.0  27962.0  30072.0
Амурская область       32902.0  33837.0  37368.0  42315.0  47234.0  52430.0
Архангельская область  35592.0  38118.0  40352.0  45427.0  49435.0  52779.0

'Реальная начисленная заработная плата, в процентах к предыдущему году'

                       2015   2016   2017   2018   2019   2020
region
Алтайский край           90   98.4  103.6  109.3  104.9  103.8
Амурская область         88   96.0  107.4  110.1  106.0  105.2
Архангельская область  92.4  100.0  102.5  110.7  104.0  102.9

### **1.3 Здоровье и заболеваемость**

> **disabled_total_by_age_2017_2022.csv** — число людей с инвалидностью по регионам, по месяцам, по возрастным группам.

Как всем известно чаще всего человек склонен к инвалидности в пенсионном возрасте, данные это подтверждают. Основную долю инвалидов занимиют люди за 60+. И тут возникает вопрос: "Стоит ли учитывать их в данных?" Я думаю нет, их состояние зачастую связанно с возрастом, поэтому удаляем признак `60_` и создаем признак `18_60`.

Будем использовать данные по концу каждого года то есть по 1 числа декабря, если таких данных нет, то берем последний который есть.

In [10]:
disabled_by_age = pd.read_csv('social_russia_data/disabled_total_by_age_2017_2022.csv')

disabled_by_age = process_region_data(disabled_by_age, standard_names)


disabled_by_age.date = pd.to_datetime(disabled_by_age.date)
# создадим признак год
disabled_by_age['year'] = disabled_by_age['date'].dt.year
# создадим признак месяц
disabled_by_age['month'] = disabled_by_age.date.dt.month 
# число людей с инвалидностью с 18 по 60 лет 
disabled_by_age['18_60'] = disabled_by_age['total'] - disabled_by_age['60_']

disabled_by_age.drop(['total', '18_30',	'31_40', '41_50', '51_60', '60_', 'date'],
                     axis=1,
                     inplace=True)

mask_month = disabled_by_age.month == 12 # месяц декабрь
mask_year = disabled_by_age.year == 2022
mask_month_2022 = disabled_by_age.month == 4

disabled_by_age = disabled_by_age[mask_month|(mask_year & mask_month_2022)]
# сводная итоговая таблица 
disabled_by_age = pd.pivot_table(
    data=disabled_by_age,
    columns='year',
    values='18_60',
    index=disabled_by_age.index
)
display(disabled_by_age.describe().round(2))

year        2017       2018       2019       2020       2021       2022
count      85.00      85.00      85.00      85.00      85.00      85.00
mean    51550.94   50230.89   49481.04   48631.78   47740.08   47309.61
std     48649.82   47942.44   47420.51   46989.13   46411.68   46084.01
min      1051.00    1062.00    1068.00    1058.00    1071.00    1064.00
25%     23238.00   22432.00   23368.00   22907.00   20777.00   20067.00
50%     34639.00   33648.00   33241.00   32694.00   31906.00   31592.00
75%     67367.00   63859.00   61597.00   60125.00   59331.00   58729.00
max    293858.00  285661.00  276233.00  271626.00  265030.00  261554.00

---

> **morbidity_2005_2020_age_disease.xls** — заболеваемость на 100 тыс. человек населения, по возрастным группам и группам заболеваний.

Данные предоставленны за промежуток с 2005 до 2016 года. Также есть данные о заболеваниях, соответсвенно, необходимо выбрать те, которые наиболее влияют на уязвимые группы населения. 

В данных присутсвует возрастная категория "Всего", однако это не просто агреггированное значение, видимо используется другая методолгия. Рассматривать в целом возрастные категории не будем, поэтому группируем данные.

Отберем заболевания, которые могли бы влиять на определение уязвимых групп населения:
-   **Все заболевания** - агреггированный показатель заболеваний региона
-   **Психические расстройства и расстройства поведения** 
-   **Болезни эндокринной системы, расстройства питания и нарушения обмена веществ**

In [11]:
morbidity = pd.read_excel(
    'social_russia_data/morbidity_2005_2020_age_disease.xls',
    header=2
)
# переименуем название столбцов 
morbidity.rename(
    {'Unnamed: 0': 'region',
     'Unnamed: 1': 'disease',
     'Unnamed: 2': 'age'},
    axis=1,
    inplace=True
)

# обрабатываем названия регионов
replacements = {
    '        Архангельская обл. без данных по Ненецкому авт. окр.': 
    'Архангельская область (без автономных округов)',
    '        Тюменская обл.без данных по Ханты-Мансийскому и Ямало-Ненецкому авт. окр.':
    'Тюменская область (без автономных округов)'
}

morbidity = morbidity.replace(replacements)


names_to_drop = [
    '        Тюменская область',
    '        Архангельская область'
]
morbidity = process_region_data(morbidity, standard_names, names_to_drop)

# убираем категорию "Всего"
mask = morbidity.age == 'Всего'
morbidity = morbidity[~mask].reset_index()

'''# 1) Подростковая беременность 
mask_pregnancy = (
    (morbidity.disease == 'Беременность, роды и послеродовой период') &
    (morbidity.age == '0-14 лет')
)

teenage_pregnancy = morbidity[mask_pregnancy].copy()
teenage_pregnancy.drop(['disease', 'age'], axis=1, inplace=True)
# группируем, так как есть дубликаты (явл. данными за 2014-2016 годы)
teenage_pregnancy = teenage_pregnancy.groupby('region').sum()'''


# удяляем признак age из исходного датасета 
morbidity.drop('age', axis=1, inplace=True)
# группированные данные без возрастных групп
morbidity = morbidity.groupby(['region', 'disease']).sum().reset_index()

# 1) Все заболевания
mask_all_disease = morbidity.disease == 'Все заболевания'
all_disease = morbidity[mask_all_disease].copy().set_index('region')

# 2) Психические расстройства и расстройства поведения
mask_mental_disorder = morbidity.disease == 'Психические расстройства и расстройства поведения'
mental_disorder = morbidity[mask_mental_disorder].copy().set_index('region')


# 3) Болезни эндокринной системы, расстройства питания и нарушения обмена веществ
mask_food_disorder = morbidity.disease == 'Болезни эндокринной системы, расстройства питания и нарушения обмена веществ'
food_disorder = morbidity[mask_food_disorder].copy().set_index('region')

'''# display('Подростковая беременность',teenage_pregnancy.head(3))'''
display('Все заболевания', all_disease.head(3))
display('Психические расстройства и расстройства поведения', mental_disorder.head(3))
display('Пищевое расстройство', food_disorder.head(3))

'Все заболевания'

,disease,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
region,,,,,,,,,,,,,
Алтайский край,Все заболевания,393458.2,406038.4,406884.3,406199.0,433971.4,414497.0,429582.3,434271.0,446182.4,446676.1,457941.9,463734.9
Амурская область,Все заболевания,283931.3,295294.4,326450.3,337911.2,368991.4,366159.7,387465.4,402330.4,390049.6,394210.7,412247.1,408636.0
Архангельская область,Все заболевания,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,537959.9,524785.5,526120.6

'Психические расстройства и расстройства поведения'

,disease,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
region,,,,,,,,,,,,,
Алтайский край,Психические расстройства и расстройства поведения,6498.0,6138.4,6050.1,5996.9,5861.8,5354.9,5527.9,5338.8,5355.9,5445.6,5675.5,5048.8
Амурская область,Психические расстройства и расстройства поведения,2915.4,2879.1,3025.3,3169.5,3075.7,3317.1,3317.5,3223.3,2863.7,2871.4,3680.1,3059.2
Архангельская область,Психические расстройства и расстройства поведения,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2740.6,2926.5,2836.1

'Пищевое расстройство'

,disease,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
region,,,,,,,,,,,,,
Алтайский край,"Болезни эндокринной системы, расстройства пита...",6604.4,7257.4,6629.9,6870.9,6399.8,6497.5,6566.7,6879.3,6894.6,7681.9,8596.4,9385.8
Амурская область,"Болезни эндокринной системы, расстройства пита...",5807.4,6262.9,6217.4,6691.2,5703.1,9022.7,6489.3,6128.4,7012.1,7621.6,6353.4,6932.5
Архангельская область,"Болезни эндокринной системы, расстройства пита...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4485.8,6804.4,6556.2

---

> **drug_alco** — сведения о заболеваемости алкоголизмом и наркоманией, на 100 тыс. населения (2005–2018).

 Речь идёт о впервые установленном диагнозе, в данном случае — о
 постановке на учёт в диспансере. То есть если в прошлом году человек
 был признан алкоголиком, в этом году он уже не учитывается в
 статистике, если стоит на учёте или вылечился и был снят с учёта. Также
 если человек не попал на учёт, хотя соответствует критериям постановки
 соответствующего диагноза, он не будет учтён в данной статистике.
 Таким образом, эти цифры занижены. Кроме того, так как показатель
 приводится именно по впервые выявленным случаям, в теории его
 можно аккумулировать (но с оговорками).

 ➔ Показатель на 100 тысяч населения — привычный показатель в
 эпидемиологии. Однако очевидно, что в данном случае он
 рассчитывается по всей популяции, хотя, возможно, такой диагноз
 ставится чаще в некоторых когортах.

 ➔ В файле четыре листа. Отдельно приводятся показатели за 2017–2018 гг.,
 так как взяты из другого источника, и там немного иначе написаны
 названия регионов

In [12]:
# чтение файлов
def readout_drug_alco(path, sheet):
    data = pd.read_excel(path, sheet_name=sheet)
    data = process_region_data(data, standard_names)
    return data

path = 'social_russia_data/drug_alco.xlsx'
alco = readout_drug_alco(path, sheet=0)
alco_1718 = readout_drug_alco(path, sheet=1)

drug = readout_drug_alco(path, sheet=2)
drug_1718 = readout_drug_alco(path, sheet=3)

alco = pd.concat([alco, alco_1718], axis=1).sort_index()
drug = pd.concat([drug, drug_1718], axis=1).sort_index()

display('Заболеваемость алкоголизмом', alco.head(3))
display('Заболеваемость наркоманией', drug.head(3))

'Заболеваемость алкоголизмом'

,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
region,,,,,,,,,,,,,,
Алтайский край,227.6,202.4,173.9,199.8,177.9,164.0,157.6,138.9,105.0,111.9,115.7,100.1,85.9,88.1
Амурская область,174.3,159.0,120.9,113.3,115.5,140.5,124.7,104.8,100.0,96.7,97.2,92.3,91.4,113.3
Архангельская область,120.1,115.2,102.5,89.8,96.5,99.5,84.4,73.2,77.6,NaN,NaN,NaN,55.3,64.7

'Заболеваемость наркоманией'

,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
region,,,,,,,,,,,,,,
Алтайский край,29.8,35.2,35.2,37.7,27.3,24.5,26.4,33.4,22.9,21.6,20.7,17.4,17.4,17.4
Амурская область,21.3,27.2,27.2,28.4,26.2,37.1,33.9,24.2,22.5,22.2,19.1,18.9,18.7,24.4
Архангельская область,1.5,1.4,1.4,2.6,3.4,4.6,6.4,4.0,4.0,NaN,NaN,NaN,5.4,9.2

### **1.4 Экономика и производство**

> **gross_regional_product_1996_2020.xls** — валовой региональный продукт на душу населения, в рублях.

*Методологическое пояснение:*
-   Объем валового регионального продукта в расчете на одного жителя субъекта Российской Федерации рассчитывается как отношение валового регионального продукта в текущих основных ценах к среднегодовой численности постоянного населения.

In [13]:
gross_product = pd.read_excel(
    'social_russia_data/gross_regional_product_1996_2020.xls',
    header=2
    )
gross_product.rename({'Unnamed: 0': 'region'}, axis=1, inplace=True)

names_to_drop = [
        '        Архангельская область',
        '        Тюменская область'
    ]

gross_product = process_region_data(
    gross_product,
    standard_names,
    names_to_drop
)

gross_product.describe().round()

,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
count,78.0,78.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,...,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0
mean,10519.0,11848.0,11978.0,19595.0,27838.0,35675.0,43897.0,54032.0,68159.0,83377.0,...,324802.0,352130.0,379841.0,421256.0,473845.0,532890.0,570172.0,661264.0,694730.0,667635.0
std,5332.0,6295.0,7841.0,13424.0,19545.0,24924.0,31694.0,40121.0,47358.0,58898.0,...,485321.0,485712.0,529821.0,585546.0,678629.0,761204.0,815470.0,1009489.0,1031437.0,813561.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,78009.0,106956.0,121986.0,125668.0,136931.0,145723.0,142200.0
25%,7420.0,8013.0,7659.0,12369.0,17660.0,23254.0,28261.0,34296.0,42889.0,51724.0,...,151178.0,169553.0,182664.0,208406.0,223161.0,258225.0,280630.0,304547.0,327149.0,342811.0
50%,9225.0,10266.0,10602.0,16311.0,23678.0,30988.0,38618.0,47934.0,58094.0,71587.0,...,222664.0,245593.0,262578.0,290822.0,317764.0,361705.0,390801.0,429668.0,449289.0,460720.0
75%,12914.0,14254.0,14394.0,23710.0,34215.0,42578.0,52241.0,63866.0,84008.0,104764.0,...,297609.0,326306.0,356311.0,379172.0,414986.0,472533.0,514001.0,568192.0,586468.0,582951.0
max,30606.0,33541.0,37859.0,70506.0,115630.0,134436.0,187368.0,256992.0,268390.0,381997.0,...,3913589.0,3685897.0,4035943.0,4329031.0,5210144.0,5964557.0,6045236.0,7296374.0,7530485.0,5206287.0

---

> **regional_production_*_*.csv** — объём отгруженных товаров собственного производства или работ/услуг, выполненных собственными силами, по видам деятельности за 2005–2016 гг., 2017–2020 гг.

In [14]:
def readout_regional_prod(path):
    data = pd.read_csv(path)
    data = process_region_data(data, standard_names, names_to_drop)
    # удаляем виды деятельности
    data.drop('production_field', axis=1, inplace=True)
    # группируем по региону
    data = data.groupby('region').sum()
    return data

regional_prod_0516 = readout_regional_prod('social_russia_data/regional_production_2005_2016.csv')
regional_prod_1720 = readout_regional_prod('social_russia_data/regional_production_2017_2020.csv')

regional_prod = pd.concat([regional_prod_0516, regional_prod_1720], axis=1)
regional_prod.head()

,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
region,,,,,,,,,,,,,,,,
Алтайский край,92619170.0,116484816.7,1.302860e+08,1.816552e+08,148133575.7,2.049478e+08,2.273109e+08,2.405824e+08,2.474189e+08,2.543375e+08,3.215263e+08,3.157819e+08,7.359764e+08,7.711927e+08,8.383179e+08,8.524434e+08
Амурская область,31814717.6,35861289.8,3.875065e+07,4.679807e+07,60866961.2,7.210232e+07,9.669124e+07,1.024127e+08,9.924642e+07,1.093931e+08,1.386028e+08,1.259368e+08,2.688441e+08,2.687608e+08,3.400267e+08,4.045765e+08
Архангельская область,0.0,0.0,0.000000e+00,0.000000e+00,0.0,1.264137e+08,1.330191e+08,1.503460e+08,2.980072e+08,1.878591e+08,2.115037e+08,4.061885e+08,7.090098e+08,6.064711e+08,5.335849e+08,6.641070e+08
Астраханская область,40922343.7,45566202.3,5.194887e+07,8.469228e+07,62969236.5,7.668357e+07,9.572381e+07,1.253555e+08,1.623128e+08,1.730122e+08,2.116270e+08,2.277982e+08,6.265697e+08,8.837665e+08,9.015147e+08,7.245978e+08
Белгородская область,156829453.7,194782787.5,2.648646e+08,3.501343e+08,295771628.7,4.157647e+08,5.043765e+08,5.289788e+08,5.293518e+08,5.818284e+08,6.728485e+08,7.210363e+08,1.566651e+09,1.790868e+09,1.878073e+09,1.948294e+09

---

> **retail_turnover_per_capita_2000_2021.xls** — оборот розничной торговли на душу населения, в рублях.

In [15]:
path = 'social_russia_data/retail_turnover_per_capita_2000_2021.xls'
retail_turnover = pd.read_excel(path, header=2, usecols='A, C:X')

retail_turnover.drop(0, axis=0, inplace=True)
retail_turnover.rename({'Unnamed: 0': 'region'}, axis=1, inplace=True)

names_to_drop = [
        '        Архангельская область',
        '            Архангельская область (без АО)',
        '        Тюменская область',
        '            Тюменская область (без АО)'
    ]

retail_turnover = process_region_data(retail_turnover, standard_names, names_to_drop)
# переводим из текстового формата в float так как есть пропуски 
retail_turnover = retail_turnover.astype(np.float64) 
retail_turnover.describe().round()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
count,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,83.0,...,83.0,83.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0
mean,11900.0,15656.0,19529.0,23931.0,30041.0,37803.0,47360.0,59766.0,77911.0,82587.0,...,121148.0,138421.0,151140.0,160795.0,165684.0,174238.0,184832.0,196911.0,199342.0,230192.0
std,7846.0,10167.0,12019.0,13990.0,16358.0,19818.0,23930.0,28405.0,34481.0,33464.0,...,42515.0,42390.0,46642.0,46585.0,46870.0,49570.0,52563.0,55465.0,56439.0,65206.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,36955.0,41805.0,46598.0,45965.0,46464.0,51027.0,51702.0,50713.0,57605.0
25%,8780.0,11302.0,14156.0,17168.0,22260.0,27946.0,33990.0,45240.0,60933.0,64838.0,...,103617.0,116171.0,124928.0,134072.0,137844.0,145186.0,153012.0,161544.0,164879.0,194191.0
50%,10872.0,14204.0,18142.0,22110.0,28294.0,35245.0,43769.0,55755.0,74184.0,81080.0,...,120844.0,134889.0,150008.0,161161.0,162400.0,170837.0,180022.0,192070.0,197028.0,223010.0
75%,13600.0,18029.0,23028.0,27809.0,34618.0,42634.0,54829.0,70458.0,92652.0,95907.0,...,138364.0,157534.0,174694.0,186603.0,195514.0,205496.0,217059.0,231113.0,232860.0,272134.0
max,68083.0,86968.0,100184.0,112698.0,128880.0,146519.0,165138.0,183163.0,210569.0,223049.0,...,305395.0,333529.0,365089.0,351448.0,346602.0,363391.0,382016.0,403426.0,408674.0,477554.0

---

> **welfare_expense_share_2015_2020** — расходы на социальную политику от общих расходов бюджета региона, % в год*.

In [16]:
path = 'social_russia_data/welfare_expense_share_2015_2020.xlsx'
welfare_expense = pd.read_excel(path)
welfare_expense = process_region_data(welfare_expense, standard_names)
welfare_expense.describe().round()

       2015  2016  2017  2018  2019  2020
count  85.0  85.0  85.0  85.0  85.0  85.0
mean   16.0  17.0  23.0  22.0  21.0  23.0
std     3.0   4.0   5.0   5.0   5.0   5.0
min     6.0   6.0   8.0   7.0   5.0   6.0
25%    14.0  15.0  21.0  21.0  19.0  22.0
50%    16.0  17.0  24.0  23.0  22.0  24.0
75%    18.0  19.0  26.0  25.0  24.0  26.0
max    22.0  29.0  31.0  30.0  30.0  35.0

### **1.5 Жилье и условия жизни**

> **housing_2020** — характеристика жилищных условий домохозяйств, оценка домохозяйствами состояния занимаемого ими жилого помещения, обследование 2020 года.

-   Таблица 1 Характеристика жилищных условий домохозяйств, % от всех домохозяйств
-   Таблица 2 Оценка домохозяйствами состояния занимаемого ими жилого помещения, % от всех домохозяйств

In [17]:
def readout_housing(path, sheet, choice_cols=None):
    data = pd.read_excel(path, sheet_name=sheet, usecols=choice_cols)
    
    data.replace('...', 0, inplace=True) # заполняем пропуски
    data = data.infer_objects(copy=False) # определяем типы данных заново 
    
    data = process_region_data(data, standard_names, region_column='Регион')
    return data

# лист 1
housing_cond = readout_housing('social_russia_data/housing_2020.xlsx',
                               sheet=0,
                               choice_cols='A, E, H')

housing_cond.columns.values[0] = 'домохозяйства с большой стесненностью'

# лист 2
housing_intent = readout_housing('social_russia_data/housing_2020.xlsx',
                                 sheet=1,
                                 choice_cols='A, C:F, H, I')

housing_intent.columns.values[0] = 'улучшить условия'
housing_intent.columns.values[1] = 'стесненность'
housing_intent.columns.values[2] = 'плохие условия'
housing_intent.columns.values[3] = 'стесненность и плохие условия'
housing_intent.columns.values[4] = 'очередь'
housing_intent.columns.values[5] = 'снос дома'

# домохозяйства, которые хотят улучшить свои жилищные условия и рассчитывающих
# на снос или очередь (отсутсвие средств)
housing_intent['отсутствие средств на улучшение'] = housing_intent[['очередь', 'снос дома']].sum(axis=1)

# из тех кто хочет улучшить условия, но не жалуется на текущие условия
housing_intent['улучшить без жалоб'] = (
    housing_intent['улучшить условия'] - 
    ((housing_intent['стесненность'] - housing_intent['стесненность и плохие условия']) +
    (housing_intent['плохие условия'] - housing_intent['стесненность и плохие условия']))
)

# Отбираем только необходимые признаки
housing_intent = housing_intent[['отсутствие средств на улучшение', 'улучшить без жалоб']].copy()
# итоговый датасет 
housing = pd.concat([housing_cond, housing_intent], axis=1)
housing.head()

,домохозяйства с большой стесненностью,Размер жилой площади в расчете на члена домохозяйства,отсутствие средств на улучшение,улучшить без жалоб
Регион,,,,
Алтайский край,3.3,18.0,5.8,8.7
Амурская область,5.9,17.3,7.3,7.9
Архангельская область,2.2,16.9,9.7,7.5
Астраханская область,3.1,19.2,17.7,10.7
Белгородская область,2.0,17.8,3.2,7.9

### **1.6 Преступность и социальное неблагополучие**

> **Папка crimes** — сведения о преступлениях, совершённых отдельными категориями лиц за 2016–2022 гг., по месяцам, регионам, категориям лиц, категориям преступлений (требует предобработки).

Будем использовать файл `4-EGS_Razdel_5_062022.xls` - самые актуальные данные о преступлениях среди предоставленных. Данные представленны с января по июнь, то есть за первое полугодие, данных за весь 2022 нет. 

Также файл не отражает полную статистику преступлений за год, она учитывает ***количество предварительно расследованных преступлений в отчетном периоде (из числа находившихся в производстве или зарегистрированных в отчетном периоде) совершенных***

In [18]:
# функция для считывания данных с таблиц о преступлениях
def readout_crimes(path, sheet, choice_cols=None):
    data = pd.read_excel(path, sheet, header=9, usecols=choice_cols)

    data.drop([0, 1], axis=0, inplace= True)
    
    # приведем названия столбцов в нормальное состояние
    data.columns.values[0] = 'region'
    data.columns.values[7] = 'ДомНасилие'
    data.columns.values[8] = 'Иностранцами'
    
    # стандартизируем названия 
    data = process_region_data(data, standard_names)
    
    # преcтупления группой лиц
    data['группой лиц'] = data[[
        'группой лиц',
        'группой лиц по предварительному сговору',
        'организованной группой',
        'преступным сообществом (преступной организацией)'
    ]].sum(axis=1)
    data.drop([
        'группой лиц по предварительному сговору',
        'организованной группой',
        'преступным сообществом (преступной организацией)'], axis=1, inplace=True)
    
    # зарегестрированные преступления
    data['Зарегистрированные преступления'] = data[[
        'несовершеннолетними или при их соучастии',
        'ранее совершавшими преступления'
    ]].sum(axis=1)
    
    data.drop([
        'несовершеннолетними или при их соучастии',
        'ранее совершавшими преступления'
    ], axis=1, inplace=True)
    
    return data


path = 'social_russia_data/crimes/4-EGS_Razdel_5_062022.xls'
choice_cols = 'B:D, F:I, M, P'
# все преступления
crimes_all = readout_crimes(path, sheet=0, choice_cols=choice_cols)

# Особо тяжкие преступления
crimes_severe = readout_crimes(path, sheet=1, choice_cols=choice_cols) 
crimes_severe.columns.values[3] = 'суровые преступления'
crimes_severe = crimes_severe[['суровые преступления']]

# Тяжкие преступления
crimes_heavy = readout_crimes(path, sheet=2, choice_cols=choice_cols)  
crimes_heavy.columns.values[3] = 'тяжкие преступления'
crimes_heavy = crimes_heavy[['тяжкие преступления']]

# Преступления против собственности 
crimes_theft = readout_crimes(path, sheet=12, choice_cols=choice_cols) 
crimes_theft.columns.values[3] = 'преступление собственности'
crimes_theft = crimes_theft[['преступление собственности']]

# преступления по отношению наркотических средств
crimes_drugs = readout_crimes(path, sheet=19, choice_cols=choice_cols)
crimes_drugs.columns.values[3] = 'оборот наркотиков'
crimes_drugs = crimes_drugs[['оборот наркотиков']]

# display('Все преступления:', crimes_all.head(3))
# display('Особо тяжкие преступления:', crimes_severe.head(3))
# display('Тяжкие преступления:', crimes_heavy.head(3))
# display('Преступления по отношению наркотических средств:', crimes_drugs.head(3))

crimes = pd.concat([
    crimes_all,
    crimes_severe,
    crimes_heavy,
    crimes_theft,
    crimes_drugs
], axis=1)

display(crimes.head())

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

,группой лиц,ДомНасилие,Иностранцами,Зарегистрированные преступления,суровые преступления,тяжкие преступления,преступление собственности,оборот наркотиков
region,,,,,,,,
Алтайский край,654.0,1747.0,143.0,8182.0,266.0,1408.0,3837.0,697.0
Амурская область,173.0,649.0,43.0,2945.0,123.0,638.0,1161.0,416.0
Архангельская область,404.0,748.0,22.0,3198.0,154.0,585.0,1584.0,164.0
Астраханская область,473.0,998.0,110.0,3070.0,363.0,410.0,972.0,220.0
Белгородская область,448.0,432.0,100.0,2746.0,107.0,357.0,1589.0,228.0

### **1.7 Сироты**

> **report_orphanhood_2022.xlsx** — [Данные](https://tochno.st/problems/orphanhood) о количестве сирот, изменении их статуса, устройству, защите их прав, количеству специалистов и организаций по охране детства.

**Показатели:**
-   Всего детей в регионе, человек
-   Нуждаются в устройстве в семьи, человек
-   Устройство детей в семьи
-   Граждан, желающих принять ребенка на воспитание в семьи
-   Отмены решений о передаче в семью, усл.ед.
-   Возвращение детей в кровные семьи, усл.ед.

Будем использовать показатель отношение сирот и всего детей в процентах

In [19]:
path = 'social_russia_data/report_orphanhood_2022.xlsx'
ophans = pd.read_excel(path, header=1)

ophans = process_region_data(ophans, standard_names, region_column='Регион')
ophans.rename({'Нуждаются в устройстве в семьи, человек': 'Сироты'}, axis=1, inplace=True)

# отношение сирот и всего детей в процентах
ophans['Сироты'] = (ophans['Сироты'] / ophans['Всего детей в регионе, человек']) * 100

ophans = ophans[['Сироты']].round(2)

ophans

                                 Сироты
Регион
Алтайский край                     0.21
Амурская область                   0.33
Архангельская область              0.35
Астраханская область               0.16
Белгородская область               0.08
...                                 ...
Чеченская Республика               0.00
Чувашская Республика — Чувашия     0.06
Чукотский автономный округ         0.75
Ямало-Ненецкий автономный округ    0.05
Ярославская область                0.20

[85 rows x 1 columns]

### **1.8 Пенсионеры**

> **report_ageing_2020.xlsx** — [Данные](https://tochno.st/problems/ageing) о людях в возрасте старше трудоспособного.

In [20]:
path = 'social_russia_data/report_ageing_2020.xlsx'
pensioner = pd.read_excel(path, header=1)

pensioner = process_region_data(pensioner, standard_names, region_column='Регион')
pensioner = pensioner['Бедные по самооценке пожилые люди, %'].to_frame()
pensioner.describe().round(2)

       Бедные по самооценке пожилые люди, %
count                                 85.00
mean                                  17.30
std                                    9.64
min                                    0.00
25%                                    9.70
50%                                   17.80
75%                                   24.00
max                                   39.80

### **1.9 Безработица**

> **unemployment.xls** — [Данные](https://www.fedstat.ru/indicator/43062) уровня безработицы.

Уровень безработицы (по методологии МОТ) - отношение численности безработных определенной возрастной группы к численности рабочей силы соответствующей возрастной группы, рассчитанное в процентах.

Будем использовать данные за 2022 год.

In [21]:
unemployment = pd.read_excel('social_russia_data/unemployment.xls', header=3, usecols='B, E:I')

unemployment.rename({
    'Unnamed: 1': 'region'
}, axis=1, inplace=True)

names_to_drop = [
        '        Архангельская область',
        '        Тюменская область'
    ]

unemployment = process_region_data(unemployment, standard_names, names_to_drop)
unemployment

,I квартал,II квартал,III квартал,IV квартал,значение показателя за год
region,,,,,
Алтайский край,4.3,3.7,3.7,3.5,3.8
Амурская область,4.5,4.3,4.2,3.5,4.1
Архангельская область,5.4,5.4,5.5,5.5,5.4
Астраханская область,7.4,7.1,7.2,6.8,7.1
Белгородская область,3.8,3.8,3.7,3.6,3.7
...,...,...,...,...,...
Чеченская Республика,11.0,11.0,11.0,11.0,11.0
Чувашская Республика — Чувашия,3.6,3.8,2.8,2.7,3.2
Чукотский автономный округ,2.4,1.3,2.1,2.0,1.9
Ямало-Ненецкий автономный округ,1.6,1.6,1.7,1.6,1.6
Ярославская область,4.8,5.5,4.9,4.8,5.0

### **1.10 Прожиточный минимум**

> **living_cost.xls** — [Данные](https://www.fedstat.ru/indicator/30957) прожиточного минимума по регионам РФ за 2020 год.

In [22]:
living_cost = pd.read_excel('social_russia_data/living_cost.xls', header=3)
living_cost.rename({'Unnamed: 0': 'region'}, axis=1, inplace=True)
living_cost.drop(0, inplace=True)

living_cost = process_region_data(living_cost, standard_names, names_to_drop)
living_cost = living_cost.astype(np.int64)
# за 2020 год 
living_cost[2020] = living_cost.mean(axis=1)
living_cost.describe().round(2)

       I квартал  II квартал  III квартал  IV квартал      2020
count      85.00       85.00        85.00       85.00     85.00
mean    11566.60    12151.02     12242.89    12037.36  11999.47
std      2892.68     2931.58      3023.88     3006.84   2960.83
min      8894.00     9362.00      9269.00     9053.00   9144.50
25%      9934.00    10483.00     10584.00    10324.00  10333.00
50%     10440.00    11134.00     11178.00    10962.00  10879.25
75%     11655.00    12341.00     12453.00    12084.00  12083.25
max     22506.00    23302.00     23860.00    23999.00  23416.75

> ## <CENTER> **Таблица датасетов**

| Dataframe            | Описание                                      | Единица измерения         | Период         |
|-----------------------|-----------------------------------------------|---------------------------|----------------|
| *child_mortality_rural* | Число умерших на первом году жизни детей в сельской местности | чел.                    | 1990–2021      |
| *child_mortality_urban* | Число умерших на первом году жизни детей в городской местности | чел.                   | 1990–2021      |
| *disabled_total_by_age* | Число людей с инвалидностью по возрастным группам | чел.                   | 2017–2022      |
| *morbidity_2005_2020_age_disease* | Заболеваемость на 100 тыс. населения по возрастным группам и заболеваниям | кол-во. / 100 тыс. населения | 2005–2020 |
| *poverty_percent_by_regions* | Процент людей, живущих за чертой бедности | %                      | 1992–2020      |
| *welfare_expense_share* | Расходы на социальную политику от общих расходов бюджета региона | %                     | 2015–2020      |
| *cash_real_income_wages* | Среднедушевые и реальные денежные доходы, номинальная и реальная зарплата | руб. / чел., % к предыдущему году | 2015–2020 |
| *poverty_socdem_2017_2020* | Распределение малоимущего населения по социально-демографическим группам | %                     | 2017–2020      |
| *housing_2020* | Жилищные условия: жилая площадь, плохое состояние, отсутствие средств | кв.м., %, %           | 2020           |
| *population* | Численность населения по регионам и федеральным округам | чел.                | 1999–2022      |
| *gross_regional_product* | Валовой региональный продукт на душу населения | руб. / чел.           | 1996–2020      |
| *regional_production* | Объём отгруженных товаров собственного производства | тыс. руб.            | 2005–2020      |
| *retail_turnover_per_capita* | Оборот розничной торговли на душу населения | руб. / чел.           | 2000–2021      |
| *drug_alco* | Заболеваемость алкоголизмом и наркоманией | кол-во. / 100 тыс. населения | 2005–2018 |
| *newborn_2006_2022_monthly* | Число рождённых в месяце (без мертворождённых) | чел.                 | 2006–2022      |
| *crimes* | Количество предварительно расследованных преступлений за 2022 год | кол-во               | 2022           |
| *report_orphanhood* | Отношение числа [сирот](https://tochno.st/problems/orphanhood) к общему числу детей | %                    | 2022           |
| *report_ageing* | [Данные](https://tochno.st/problems/ageing) о людях в возрасте старше трудоспособного. | %                 | 2020           |
| *unemployment* | [Данные](https://www.fedstat.ru/indicator/43062) уровня безработицы. | %                     | 2022           |
| *living_cost* | [Данные](https://www.fedstat.ru/indicator/30957) прожиточного минимума по регионам РФ за 2020 год. | руб. / чел.         | 2020           |

> ## <CENTER> **Итоговый датасет**

| Признак                     | Описание                                              | Единица измерения          |
|------------------------------|-------------------------------------------------------|----------------------------|
| ***population***             | Численность населения по регионам РФ                  | чел                        |
| newborn                      | рожденные в том году, без учёта мертворождённых       | чел                        |
| child_mortality              | число умерших на первом году жизни детей за год      | чел                        |
| ***poverty_percent***        | процент людей, живущих за чертой бедности, оценка за год | %                       |
| poverty_children             | процент детей среди малообеспеченного населения      | %                          |
| poverty_pensioners           | процент пенсионеров среди малообеспеченного населения | %                          |
| poverty_labouring            | процент людей трудоспособного возраста среди малообеспеченного населения | %                  |
| per_capita_cash_income       | Cреднедушевые денежные доходы (в месяц), руб.         | руб.                       |
| real_income                  | Реальные денежные доходы, в процентах к предыдущему году | %                       |
| formal_wage_paid             | Cреднемесячная номинальная начисленная заработная плата, руб. | руб.               |
| real_pay                     | Реальная начисленная заработная плата, в процентах к предыдущему году | %                  |
| disabled_by_age              | число людей от 18 до 60 с инвалидностью               | чел                        |
| all_disease                  | все заболевания на 100 тыс чел                        | кол-во. / 100 тыс. населения |
| mental_disorder              | психическое расстройство на 100 тыс чел               | кол-во. / 100 тыс. населения |
| food_disorder                | пищевое расстройство на 100 тыс чел                   | кол-во. / 100 тыс. населения |
| disease_alco                 | заболеваемость алкоголизмом на 100 тыс чел            | кол-во. / 100 тыс. населения |
| disease_drug                 | заболеваемость наркоманией на 100 тыс чел             | кол-во. / 100 тыс. населения |
| ***gross_product***          | валовый региональный продукт на душу населения, в рублях | руб на чел              |
| regional_prod                | объём отгруженных товаров собственного производства или работ/услуг, выполненных собственными силами, по видам деятельности | тыс. руб.               |
| retail_turnover              | оборот розничной торговли на душу населения, в рублях | руб на чел              |
| welfare_expense              | расходы на социальную политику от общих расходов бюджета региона, % в год | %                   |
| housing_constraints          | процент домохозяйств с большой стесненностью          | % от всех домохозяйств     |
| housing_area_per_person      | Размер общей площади в расчете на члена домохозяйства | кв метры                   |
| no_improvement_funds         | процент домохозяйств, которые хотят улучшить свои жилищные условия и рассчитывающих на снос или очередь (отсутсвие средств) | % от всех домохозяйств     |
| improvement_without_complaints | процент домохозяйств, которые хотят улучшить условия, но не имеют жалоб на текущие условия | %                      |
| group_crimes                 | количество преступлений совершенных группой лиц       | кол-во                     |
| domestic_violence            | количество преступлений совершенных членом семьи, супругом, сожителем, сексуальным партнером (в том числе бывшими) | кол-во                     |
| foreign_crimes               | количество преступлений совершенных иностранцами      | кол-во                     |
| registered_crimes            | количество зарегистрированных преступлений            | кол-во                     |
| crimes_severe                | количество совершенных особо тяжких преступлений      | кол-во                     |
| crimes_heavy                 | количество совершенных тяжких преступлений            | кол-во                     |
| crimes_theft                 | количество совершенных преступлений против собственности | кол-во                  |
| crimes_drugs                 | количество совершенных преступлений по отношению наркотических средств | кол-во             |
| ophans                       | процентов сирот в регионе                           | %                          |
| poor_pensioner               | Бедные по самооценке пожилые люди                     | %                          |
| unemployment                 | уровень безработицы (МОТ)                             | %                          |
| min_living_cost              | прожиточный минимум                                   | руб на чел                  |

При создании итогового датасета будем использовать самые актуальные данные (по возможности). В основном будем брать данные за 2020 и 2022 год. 

**Альтернативный вариант**: брать значения за год, который представлен более полно, к примеру 2020 год. Однако, при класстеризации регионов РФ по уязвимым группам населения, необходимо ссылаться на самые последние данные. 

Класстеризация по уязвимым регионам, необходима для принятия важных решений, возможно, именно от этих решений зависят жизни людей. Рассматривая идеально возможный вариант, можно было бы найти и использовать самые актуальные данные, но так как были предоставленны определенные датасеты и это дипломный проект, в качестве исследования будем использовать текущие данные.

In [23]:
# Начальный список датасетов
datasets = [
    population[[2022]].rename({2022: 'population'}, axis=1),         
    newborn[[2021]].rename({2021: 'newborn'}, axis=1),             
    child_mortality[['2021']].rename({'2021': 'child_mortality'}, axis=1),     
    poverty_percent[[2020]].rename({2020: 'poverty_percent'}, axis=1),  
    
    poverty_socdem_2020.rename({
        'children': 'poverty_children',
        'pensioners': 'poverty_pensioners',
        'labouring': 'poverty_labouring'}, axis=1),   
    
    per_capita_cash_income[[2020]].rename({2020: 'per_capita_cash_income'}, axis=1),  
    real_income[[2020]].rename({2020: 'real_income'}, axis=1),          
    formal_wage_paid[[2020]].rename({2020: 'formal_wage_paid'}, axis=1),     
    real_pay[[2020]].rename({2020: 'real_pay'}, axis=1),        
         
    disabled_by_age[[2022]].rename({2022: 'disabled_by_age'}, axis=1),  

    all_disease[['2016']].rename({'2016': 'all_disease'}, axis=1), 
    mental_disorder[['2016']].rename({'2016': 'mental_disorder'}, axis=1),  
    food_disorder[['2016']].rename({'2016': 'food_disorder'}, axis=1),   
     
    alco[[2018]].rename({2018: 'disease_alco'}, axis=1),                       
    drug[[2018]].rename({2018: 'disease_drug'}, axis=1),     
                      
    gross_product[['2020']].rename({'2020': 'gross_product'}, axis=1),         
    regional_prod[['2020']].rename({'2020': 'regional_prod'}, axis=1),            
    retail_turnover[['2021']].rename({'2021': 'retail_turnover'}, axis=1),   
    welfare_expense[[2020]].rename({2020: 'welfare_expense'}, axis=1),
            
    housing[['домохозяйства с большой стесненностью']].rename(
        {'домохозяйства с большой стесненностью': 'housing_constraints'}, axis=1),  
    housing[['Размер жилой площади в расчете на члена домохозяйства']].rename(
        {'Размер жилой площади в расчете на члена домохозяйства': 'housing_area_per_person'}, axis=1),  
    housing[['отсутствие средств на улучшение']].rename(
        {'отсутствие средств на улучшение': 'no_improvement_funds'}, axis=1),  
    housing[['улучшить без жалоб']].rename({'улучшить без жалоб': 'improvement_without_complaints'}, axis=1),
    
    crimes.rename({
        'группой лиц': 'group_crimes',
        'ДомНасилие': 'domestic_violence',
        'Иностранцами': 'foreign_crimes',
        'Зарегистрированные преступления': 'registered_crimes',
        'суровые преступления': 'crimes_severe',
        'тяжкие преступления': 'crimes_heavy',
        'преступление собственности': 'crimes_theft',
        'оборот наркотиков': 'crimes_drugs',
    }, axis=1),
    
    ophans.rename({'Сироты': 'ophans'}, axis=1),                    
    pensioner.rename({'Бедные по самооценке пожилые люди, %': 'poor_pensioner'}, axis=1),                 
    unemployment[['значение показателя за год']].rename({'значение показателя за год': 'unemployment'}, axis=1),                    
    living_cost[[2020]].rename({2020: 'min_living_cost'}, axis=1)                   
]
df_regions = pd.concat(datasets, axis=1)
df_regions

,population,newborn,child_mortality,poverty_percent,poverty_children,poverty_pensioners,poverty_labouring,per_capita_cash_income,real_income,formal_wage_paid,...,foreign_crimes,registered_crimes,crimes_severe,crimes_heavy,crimes_theft,crimes_drugs,ophans,poor_pensioner,unemployment,min_living_cost
Алтайский край,2268179.0,18992.00,88.0,17.50,31.4,9.2,59.4,23864.0,95.5,30072.0,...,143.0,8182.0,266.0,1408.0,3837.0,697.0,0.21,28.1,3.8,10281.00
Амурская область,772525.0,7343.00,36.0,15.20,38.4,4.7,56.9,35499.0,100.3,52430.0,...,43.0,2945.0,123.0,638.0,1161.0,416.0,0.33,29.2,4.1,13071.50
Архангельская область,1069782.0,8487.00,32.0,12.55,28.5,7.2,64.3,34852.0,98.4,52779.0,...,22.0,3198.0,154.0,585.0,1584.0,164.0,0.35,13.0,5.4,13421.50
Астраханская область,989430.0,10709.00,46.0,15.60,42.1,5.5,52.4,25199.0,97.1,38885.0,...,110.0,3070.0,363.0,410.0,972.0,220.0,0.16,8.2,7.1,10716.25
Белгородская область,1531917.0,12223.00,54.0,7.20,44.8,12.9,42.3,32841.0,98.1,37442.0,...,100.0,2746.0,107.0,357.0,1589.0,228.0,0.08,0.8,3.7,9401.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Чеченская Республика,1516387.0,30344.99,197.0,20.40,43.7,6.2,50.1,24596.0,100.1,29771.0,...,3.0,361.0,2.0,65.0,143.0,66.0,0.00,13.0,11.0,11229.75
Чувашская Республика — Чувашия,1198429.0,11063.98,29.0,16.80,22.2,4.2,73.6,21155.0,101.4,31844.0,...,35.0,2406.0,76.0,341.0,1250.0,78.0,0.06,6.9,3.2,9664.00
Чукотский автономный округ,50040.0,521.00,8.0,8.00,51.0,0.0,49.0,89541.0,105.2,120641.0,...,4.0,160.0,12.0,33.0,62.0,2.0,0.75,15.7,1.9,23416.75
Ямало-Ненецкий автономный округ,552117.0,6950.00,32.0,4.80,51.0,0.7,48.4,89928.0,106.8,111216.0,...,45.0,1157.0,83.0,246.0,422.0,106.0,0.05,4.6,1.6,16541.00
Ярославская область,1227383.0,10238.00,38.0,9.90,31.9,2.3,65.8,29514.0,98.2,37820.0,...,83.0,2884.0,122.0,503.0,1725.0,146.0,0.20,29.6,5.0,10600.25

In [24]:
df_regions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 85 entries, Алтайский край to Ярославская область
Data columns (total 37 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   population                      85 non-null     float64
 1   newborn                         85 non-null     float64
 2   child_mortality                 85 non-null     float64
 3   poverty_percent                 85 non-null     float64
 4   poverty_children                85 non-null     float64
 5   poverty_pensioners              85 non-null     float64
 6   poverty_labouring               85 non-null     float64
 7   per_capita_cash_income          85 non-null     float64
 8   real_income                     85 non-null     float64
 9   formal_wage_paid                85 non-null     float64
 10  real_pay                        85 non-null     float64
 11  disabled_by_age                 85 non-null     float64
 12  all_disease                     85 non-null     float64
 13  mental_disorder                 85 non-null     float64
 14  food_disorder                   85 non-null     float64
 15  disease_alco                    85 non-null     object
 16  disease_drug                    85 non-null     object
 17  gross_product                   85 non-null     float64
 18  regional_prod                   85 non-null     float64
 19  retail_turnover                 85 non-null     float64
 20  welfare_expense                 85 non-null     float64
 21  housing_constraints             85 non-null     float64
 22  housing_area_per_person         85 non-null     float64
 23  no_improvement_funds            85 non-null     float64
 24  improvement_without_complaints  85 non-null     float64
 25  group_crimes                    85 non-null     float64
 26  domestic_violence               85 non-null     float64
 27  foreign_crimes                  85 non-null     float64
 28  registered_crimes               85 non-null     float64
 29  crimes_severe                   85 non-null     float64
 30  crimes_heavy                    85 non-null     float64
 31  crimes_theft                    85 non-null     float64
 32  crimes_drugs                    85 non-null     float64
 33  ophans                          85 non-null     float64
 34  poor_pensioner                  85 non-null     float64
 35  unemployment                    85 non-null     float64
 36  min_living_cost                 85 non-null     float64
dtypes: float64(35), object(2)
memory usage: 25.2+ KB

In [25]:
# проверим наличие дубликатов
df_regions.duplicated().value_counts()

False    85
Name: count, dtype: int64

In [26]:
# преобразуем object в float
df_regions.disease_alco = df_regions.disease_alco.astype(float)
df_regions.disease_drug = df_regions.disease_drug.astype(float)

df_regions.info()

<class 'pandas.core.frame.DataFrame'>
Index: 85 entries, Алтайский край to Ярославская область
Data columns (total 37 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   population                      85 non-null     float64
 1   newborn                         85 non-null     float64
 2   child_mortality                 85 non-null     float64
 3   poverty_percent                 85 non-null     float64
 4   poverty_children                85 non-null     float64
 5   poverty_pensioners              85 non-null     float64
 6   poverty_labouring               85 non-null     float64
 7   per_capita_cash_income          85 non-null     float64
 8   real_income                     85 non-null     float64
 9   formal_wage_paid                85 non-null     float64
 10  real_pay                        85 non-null     float64
 11  disabled_by_age                 85 non-null     float64
 12  all_disease                     85 non-null     float64
 13  mental_disorder                 85 non-null     float64
 14  food_disorder                   85 non-null     float64
 15  disease_alco                    85 non-null     float64
 16  disease_drug                    85 non-null     float64
 17  gross_product                   85 non-null     float64
 18  regional_prod                   85 non-null     float64
 19  retail_turnover                 85 non-null     float64
 20  welfare_expense                 85 non-null     float64
 21  housing_constraints             85 non-null     float64
 22  housing_area_per_person         85 non-null     float64
 23  no_improvement_funds            85 non-null     float64
 24  improvement_without_complaints  85 non-null     float64
 25  group_crimes                    85 non-null     float64
 26  domestic_violence               85 non-null     float64
 27  foreign_crimes                  85 non-null     float64
 28  registered_crimes               85 non-null     float64
 29  crimes_severe                   85 non-null     float64
 30  crimes_heavy                    85 non-null     float64
 31  crimes_theft                    85 non-null     float64
 32  crimes_drugs                    85 non-null     float64
 33  ophans                          85 non-null     float64
 34  poor_pensioner                  85 non-null     float64
 35  unemployment                    85 non-null     float64
 36  min_living_cost                 85 non-null     float64
dtypes: float64(37)
memory usage: 25.2+ KB

**Выводы:**
-   Пропуски отсутствуют
-   Дубликаты отсутствуют
-   Все столбцы имеют тип данных float64.

In [27]:
# # сохраняем итоговый датасет 
df_regions.to_csv('social_russia_data/df_regions_1.csv')